return {
	{
		name = "dead_bunny",
		form = "image",
		file = "resources/images/dead_bunny_nw.png",
		xScale = 0.23,
		yScale = 0.23,
		xOffset = 0.5,
		yOffset = 0.68,
	},
	{
		name = "dead_bear",
		form = "image",
		file = "resources/images/dead_rocketbear_ne.png",
		xScale = 0.28,
		yScale = 0.28,
		xOffset = 0.5,
		yOffset = 0.5,
	},
	{
		name = "dead_car_red",
		form = "image",
		file = "resources/images/dead_car_blue_sw.png",
		xScale = 0.23,
		yScale = 0.23,
		xOffset = 0.5,
		yOffset = 0.5,
	},
	{
		name = "dead_car_blue",
		form = "image",
		file = "resources/images/dead_car_blue_sw.png",
		xScale = 0.3,
		yScale = 0.3,
		xOffset = 0.5,
		yOffset = 0.5,
	},
	{
		name = "dead_spider",
		form = "image",
		file = "resources/images/dead_spider.png",
		xScale = 0.7,
		yScale = 0.7,
		xOffset = 0.5,
		yOffset = 0.5,
	},
	{
		name = "dead_enemy_croc",
		form = "image",
		file = "resources/images/dead_boss_croc.png",
		xScale = 0.5,
		yScale = 0.5,
		xOffset = 0.5,
		yOffset = 0.5,
	},
}
