return {
	{
		name = "health_down",
		file = "resources/images/effects/health_down.png",
		form = "animation",
		xScale = 1,
		yScale = 1,
		width = 500,
		duration = 0.4,
		xOffset = 0,
		yOffset = 0,
	},
	{
		name = "health_up",
		file = "resources/images/effects/health_up.png",
		form = "animation",
		xScale = 1,
		yScale = 1,
		width = 500,
		duration = 0.4,
		xOffset = 0,
		yOffset = 0,
	},
	{
		name = "get_spell",
		file = "resources/images/effects/explosion.png",
		form = "animation",
		xScale = 0.42,
		yScale = 0.42,
		width = 400,
		duration = 0.4,
	},
}
