
-- resource forms: image, sound, animation, iso_image, iso_animation

return {
	"test_anim",
	"spell_interface",
	"spell_croc",
	"croc",
	"test_iso_image",
	"tree_1",
	"rock_1",
	"rock_2",
	"bush_1",
	"grass_1",
	"grass_2",
	"rocket_bear",
	"background_1",
	"background_2",
	"fireball_icon",
	"snake_icon",
	"wisp_icon",
	"shotgun_icon",
    "haste_icon",
    "cantrip_icon",
    "seeker_icon",
    "shield_icon",
    "shotgun",
    "shield",
    "shield_damaged",
    "seeker",
    "wisp",
    "fireball",
    "serpent",
    "cantrip",
	"spell_anim",
	"shape_n",
	"health",
	"dead_croc",
	"stun",
	"car",
	"bunny",
	"projectiles",
	"interface_anim",
	"explosions",
	"dust",
	"car_blue",
	"bear_car",
}
